---
- hosts: all
  become: true
  tasks:
    - name: installing java in  ubuntu
      apt:
         name: "{{ java_ubuntu }}"
         state: present
         update_cache: yes
      when: ansible_os_family == "Debian"

    - name: installing java in  rhel
      yum:
         name: "{{ java_rhel }}"
         state: present
         update_cache: yes
      when: ansible_os_family == "RedHat"

